### ISSUE TITLE
t/11_simple.t fails

### ISSUE THREAD

**Issue by eserte** [ytnobody/Vector-QRCode-IntoPDF#2]
t/11_simple.t fails:
```
#          got: '%PDF-1.4
# %Ã¤Ã¼Ã¶Ã
# 2 0 obj
# <</Length 3 0 R/Filter/FlateDecode>>
# stream
# xµRMkÃ0½ûWè\'ù;M×zëØaì¶u£¤õÒ¿?ÉIWÒÂÃÄ¶¢÷e¡&8ªO@@ÞùÚkÉNpxU3øP2o
(... full PDF contents following ...)
# startxref
# 9422
# %%EOF
# '
# Looks like you failed 1 test of 2.
t/11_simple.t ... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by ytnobody** [comment]
@eserte 
Thanks for reporting.

It was caused by difference of PDF version (expected PDF v1.3, but PDF v1.4 provoked data differences when testing).

It became resolved in v0.03.

Best regards.

**Comment by eserte** [comment]
Unfortunately I see still fails of t/11_simple.t, but not everywhere. 
See also http://fast-matrix.cpantesters.org/?dist=Vector-QRCode-IntoPDF%200.03

**Comment by ytnobody** [comment]
Thanks for reporting.

Maybe, logic to detect PDF version was not work as expected.

I going to try another solution.

**Comment by ytnobody** [comment]
@eserte On 0.05, `t/11_simple.t` has renamed as `xt/11_simple.t`.
And It looks no failure in testing matrix.
http://matrix.cpantesters.org/?dist=Vector-QRCode-IntoPDF
